### ISSUE TITLE
Send a release

### ISSUE THREAD

**Issue by hamrak** [websygen/owfont#2]
The requested bower package "owfont" could not be found in any version, there may be a typo in the package name. If you wan fix this issue, put a release tag into next push please.

http://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by Addvilz** [comment]
The error message you gave is from Composer, I guess with `composer-asset-plugin` installed, not Bower.

Bower installs master version just fine, by issuing `bower install owfont` or `bower install owfont#master` or by including `"owfont": "master"` in your dependencies, and it is perfectly valid to do so.

**Comment by hamrak** [comment]
Yes, but "master" is not a stable release ... it is only "dev-master" - developer release ... bower is not so strictly as composer assets plugin.

**Comment by Addvilz** [comment]
It is actually complete opposite: master is and has been a "latest stable" in all traditional GIT workflows, it's just that a lot of developers have started to use it as a rolling release staging branch, especially popular in PHP ecosystem. 

That is probably why Composer folks decided to not to pay special attention to master. It also makes sense in a lot of projects not to use master because of backwards compatibility - stuff can and would change between versions, incompatible API's, etc. 

In this project - I don't think it will ever affect us. And doing something religiously only because some guy somewhere said depending on master is bad is a rather silly thing to do - especially, in this case.
